# Generated by Django 5.0.2 on 2024-03-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "documents",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                ("address", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("experts", models.CharField(max_length=200)),
            ],
        ),
    ]
