# Generated by Django 5.0.2 on 2024-04-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
