# Generated by Django 4.2.7 on 2024-07-19 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_enquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
