# Generated by Django 4.2.7 on 2024-07-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='bio',
        ),
        migrations.AddField(
            model_name='expert',
            name='citizenship_back',
            field=models.ImageField(blank=True, null=True, upload_to='users/license'),
        ),
        migrations.AddField(
            model_name='expert',
            name='citizenship_front',
            field=models.ImageField(blank=True, null=True, upload_to='users/citicenship_photo'),
        ),
        migrations.AddField(
            model_name='expert',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/passport_photo'),
        ),
    ]
