# Generated by Django 4.2.7 on 2024-07-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_expert_bio_expert_citizenship_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='citizenship_back',
            field=models.ImageField(blank=True, null=True, upload_to='experts/license'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='citizenship_front',
            field=models.ImageField(blank=True, null=True, upload_to='experts/citicenship_photo'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='experts/passport_photo'),
        ),
    ]
